import Head from "next/head";
import React from "react";
import Navbar from "../../components/navbar/Navbar";
import Currency from "react-currency-formatter";

function productDetails({ product }: any) {
  return (
    <div>
      <Head>
        <title>amazon | product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className=" md:max-w-screen-xl p-5 mx-auto">
        <div className="grid md:grid-cols-2 gap-10">
          <div>
            <div className="h-40 xl:h-96">
              <img className="h-full object-contain mx-auto" src={product.image} alt="" />
            </div>
          </div>
          <div>
            <h1 className="text-xl font-semibold text-watchDogPrimary">
              {product.title}
            </h1>
            <p className="mt-3 text-gray-600 font-semibold">
              {product.description}
            </p>
            <p className="mt-5 text-2xl">
              <Currency quantity={product.price} currency="USD" />
            </p>
            <button className="btn text-sm mt-3">Add to basket</button>
          </div>
        </div>
      </main>
    </div>
  );
}

export const getServerSideProps = async ({ params }: any) => {
  const res = await fetch(
    `https://fakestoreapi.com/products/${params.id}`
  ).then((res) => res.json());
  return {
    props: {
      product: res,
    },
  };
};

export default productDetails;
