import Head from "next/head";
import React, { useState, useEffect } from "react";
import Navbar from "../../components/navbar/Navbar";
import Counter from "../../components/shared/Counter";
import Ratting from "../../components/shared/Ratting";

function productDetails({ product }: any) {
  const [quantity, setQuantity] = useState(1);
  useEffect(()=>{
    setQuantity(Math.floor(Math.random() * 20))
  },[])
  return (
    <div>
      <Head>
        <title>amazon | product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className=" md:max-w-screen-xl p-5 mx-auto">
        <div className="grid md:grid-cols-2 gap-10">
          <div>
            <div className="h-40 xl:h-96">
              <img
                className="h-full object-contain mx-auto"
                src={product.image}
                alt={product.title}
              />
            </div>
          </div>
          <div>
            <h1 className="text-xl mb-3 font-semibold text-watchDogPrimary">
              {product.title}
            </h1>
            <Ratting rating={product.rating} />
            <p className="mt-3 text-gray-600 font-semibold">
              {product.description}
            </p>
            <div className="mt-5 text-2xl">
              <h1>${product.price}</h1>
            </div>
            <div className="my-3">
              {quantity > 0 ? (
                <p className="text-green-700">Instock ({quantity} product)</p>
              ) : (
                <p className="text-red-500">out of stock</p>
              )}
            </div>
            <Counter price={product.price} quantity={quantity} />
          </div>
        </div>
      </div>
    </div>
  );
}

export const getServerSideProps = async ({ params }: any) => {
  const res = await fetch(
    `https://fakestoreapi.com/products/${params.id}`
  ).then((res) => res.json());
  return {
    props: {
      product: res,
    },
  };
};

export default productDetails;
