import Head from 'next/head'
import Banner from '../components/home/Banner'
import Product from '../components/home/Product'
import Navbar from '../components/navbar/Navbar'
import styles from '../styles/Home.module.css'

export default function Home({products} : any) {
  return (
    <div className='bg-gray-100'>
      <Head>
        <title>amazon-by mridul</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         <Navbar />
      <main>
        <Banner />
        <Product products={products} />
      </main>
    </div>
  )
}

export async function getServerSideProps(context : any) {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );
  return {
    props: {
      products,
    },
  };
}